# Generated by Django 2.2.7 on 2019-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imagefile', models.FileField(null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(default='bg.jpg', upload_to='photos'),
        ),
    ]
