# Generated by Django 2.2.7 on 2019-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20191121_2201'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='report',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='cover',
            field=models.ImageField(default='bg.jpg', upload_to='images/'),
        ),
    ]
