# Generated by Django 2.2.7 on 2019-11-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20191121_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='photo',
        ),
        migrations.AlterField(
            model_name='report',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
